//Write a C program to generate machine code from an abstract syntax tree generated by the parser.
// Example AST for the expression: (2 * (3 + 4)) - 5
#include <stdio.h>
#include <stdlib.h>


typedef enum {
    OPERATOR_ADD,
    OPERATOR_SUB,
    OPERATOR_MUL,
    OPERATOR_DIV,
    OPERAND_CONST
} NodeType;


typedef struct Node {
    NodeType type;
    int value;  // For operands
    struct Node *left;
    struct Node *right;
} Node;


Node *createNode(NodeType type, int value, Node *left, Node *right) {
    Node *node = (Node *)malloc(sizeof(Node));
    node->type = type;
    node->value = value;
    node->left = left;
    node->right = right;
    return node;
}


void generateMachineCode(Node *root) {
    if (root == NULL) {
        return;
    }

    if (root->type == OPERAND_CONST) {
        printf("PUSH %d\n", root->value);
    } else {
        generateMachineCode(root->left);
        generateMachineCode(root->right);


        switch (root->type) {
            case OPERATOR_ADD:
                printf("ADD\n");
                break;
            case OPERATOR_SUB:
                printf("SUB\n");
                break;
            case OPERATOR_MUL:
                printf("MUL\n");
                break;
            case OPERATOR_DIV:
                printf("DIV\n");
                break;
            default:
                fprintf(stderr, "Unknown operator type\n");
                exit(EXIT_FAILURE);
        }
    }
}


void deleteTree(Node *root) {
    if (root != NULL) {
        deleteTree(root->left);
        deleteTree(root->right);
        free(root);
    }
}

int main() {
    Node *root = createNode(OPERATOR_SUB,
                             0, // Value is not used for operators
                             createNode(OPERATOR_MUL, 0,
                                        createNode(OPERAND_CONST, 2, NULL, NULL),
                                        createNode(OPERATOR_ADD, 0,
                                                   createNode(OPERAND_CONST, 3, NULL, NULL),
                                                   createNode(OPERAND_CONST, 4, NULL, NULL))),
                             createNode(OPERAND_CONST, 5, NULL, NULL));


    generateMachineCode(root);


    deleteTree(root);

    return 0;
}